import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from 'sonner';
import Providers from "@/components/Provider";
import Navbar from "@/components/NavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
    >
      <body className="h-dvh max-w-4xl flex flex-col items-center mx-auto gap-8">
        <header className="w-full">
          <Navbar />
        </header>
        <main className="min-h-0 w-full flex-1">
          <Providers>
            {children}
          </Providers>
          <Toaster />
        </main>
        <footer></footer>
      </body>
    </html>
  );
}
